services:
  nyaya_postgres_db:
    image: postgres:16.10-alpine3.21
    container_name: nyaya_postgres_db
    volumes:
      - /opt/postgres_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=${DB_NAME:-vidhi_ai_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
      - TZ=${TZ:-UTC}
      
    ports:
      - "${DB_PORT:-5432}:5432"

    mem_limit: 4g
    mem_reservation: 2g
    cpus: "2.0"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped